// GENERATED by fincrime export-csv --constraints. Do not edit.
// Applied after the bulk import, never before: uniqueness constraints
// on 30M nodes are far cheaper to build once over existing data than
// to enforce per-row during the load.

// Institution
CREATE CONSTRAINT institution_key IF NOT EXISTS FOR (n:Institution) REQUIRE n.institution_id IS UNIQUE;

// Jurisdiction
CREATE CONSTRAINT jurisdiction_key IF NOT EXISTS FOR (n:Jurisdiction) REQUIRE n.code IS UNIQUE;

// Address
CREATE CONSTRAINT address_key IF NOT EXISTS FOR (n:Address) REQUIRE n.address_id IS UNIQUE;

// PhoneNumber
CREATE CONSTRAINT phone_number_key IF NOT EXISTS FOR (n:PhoneNumber) REQUIRE n.phone_id IS UNIQUE;
CREATE INDEX phone_number_e164 IF NOT EXISTS FOR (n:PhoneNumber) ON (n.e164);

// Individual
CREATE CONSTRAINT individual_key IF NOT EXISTS FOR (n:Individual) REQUIRE n.individual_id IS UNIQUE;
CREATE INDEX individual_tax_id IF NOT EXISTS FOR (n:Individual) ON (n.tax_id);

// LegalEntity
CREATE CONSTRAINT legal_entity_key IF NOT EXISTS FOR (n:LegalEntity) REQUIRE n.entity_id IS UNIQUE;
CREATE INDEX legal_entity_registration_number IF NOT EXISTS FOR (n:LegalEntity) ON (n.registration_number);

// Account
CREATE CONSTRAINT account_key IF NOT EXISTS FOR (n:Account) REQUIRE n.account_id IS UNIQUE;
CREATE INDEX account_iban IF NOT EXISTS FOR (n:Account) ON (n.iban);
CREATE INDEX account_opened_on IF NOT EXISTS FOR (n:Account) ON (n.opened_on);

// Card
CREATE CONSTRAINT card_key IF NOT EXISTS FOR (n:Card) REQUIRE n.card_id IS UNIQUE;

// Merchant
CREATE CONSTRAINT merchant_key IF NOT EXISTS FOR (n:Merchant) REQUIRE n.merchant_id IS UNIQUE;
CREATE INDEX merchant_mcc IF NOT EXISTS FOR (n:Merchant) ON (n.mcc);

// Device
CREATE CONSTRAINT device_key IF NOT EXISTS FOR (n:Device) REQUIRE n.device_id IS UNIQUE;
CREATE INDEX device_fingerprint IF NOT EXISTS FOR (n:Device) ON (n.fingerprint);

// IpAddress
CREATE CONSTRAINT ip_address_key IF NOT EXISTS FOR (n:IpAddress) REQUIRE n.ip_id IS UNIQUE;
CREATE INDEX ip_address_address IF NOT EXISTS FOR (n:IpAddress) ON (n.address);

// Transaction
CREATE CONSTRAINT transaction_key IF NOT EXISTS FOR (n:Transaction) REQUIRE n.txn_id IS UNIQUE;
CREATE INDEX transaction_booked_at IF NOT EXISTS FOR (n:Transaction) ON (n.booked_at);
CREATE INDEX transaction_channel IF NOT EXISTS FOR (n:Transaction) ON (n.channel);

// Ring  // GROUND TRUTH
CREATE CONSTRAINT ring_key IF NOT EXISTS FOR (n:Ring) REQUIRE n.ring_id IS UNIQUE;
CREATE INDEX ring_typology IF NOT EXISTS FOR (n:Ring) ON (n.typology);

// TypologyLabel  // GROUND TRUTH
CREATE CONSTRAINT typology_label_key IF NOT EXISTS FOR (n:TypologyLabel) REQUIRE n.label_id IS UNIQUE;
CREATE INDEX typology_label_subject_id IF NOT EXISTS FOR (n:TypologyLabel) ON (n.subject_id);
CREATE INDEX typology_label_typology IF NOT EXISTS FOR (n:TypologyLabel) ON (n.typology);
CREATE INDEX typology_label_polarity IF NOT EXISTS FOR (n:TypologyLabel) ON (n.polarity);

// CaseNarrative  // GROUND TRUTH
CREATE CONSTRAINT case_narrative_key IF NOT EXISTS FOR (n:CaseNarrative) REQUIRE n.narrative_id IS UNIQUE;
